### ISSUE TITLE
著作権について

### ISSUE THREAD

**Issue by kazoo0104** [fura2/mondegreen-distance#1]
お世話になります。
本ソースコードを、とあるプロジェクトで利用できれば嬉しいのですが、構いませんでしょうか？

**Comment by fura2** [comment]
こんにちは。
基本的に自由に使っていただいて構わないのですが、後でトラブルにならないようにライセンスを明示しておきました。
ある程度柔軟に対応できると思いますので、もし何か不都合などあればおっしゃってください。

**Comment by kazoo0104** [comment]
ありがとうございます！
